ValorantSln/Components/AgentNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ValorantWebsite.Models;

namespace ValorantWebsite.Components
{
    public class AgentNavigationViewComponent : ViewComponent
    {
        private IValorantRepository repository;

        public AgentNavigationViewComponent(IValorantRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedRole = RouteData?.Values["role"];

            return View(repository.Agents
                .Select(x => x.Role)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

ValorantSln/Controllers/AgentController.cs
using Microsoft.AspNetCore.Mvc;
using ValorantWebsite.Models;
using ValorantWebsite.Models.ViewModels;

namespace ValorantWebsite.Controllers
{
    public class AgentController : Controller
    {
        private IValorantRepository repository;

        public int PageSize = 4;

        public AgentController(IValorantRepository repo)
        {
            repository = repo;
        }

        public ViewResult AgentList(string? role, int agentPage = 1)
        => View(new AgentsListViewModel
        {
            Agents = repository.Agents
                .Where(a => role == null || a.Role == role)
                .OrderBy(a => a.AgentID)
                .Skip((agentPage - 1) * PageSize)
                .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                CurrentPage = agentPage,
                ItemsPerPage = PageSize,
                TotalItems = role == null
                ? repository.Agents.Count()
                : repository.Agents.Where(e => e.Role == role).Count()
            },
            CurrentRole = role
        });
    }
}

ValorantSln/Views/Shared/AgentSummary.cshtml
@model Agent

<div class="card card-outline-primary m-1 p-1">
    <div class="row">

        <div class="col-6">
            <div class="bg-faded p-1" style="display: flex; justify-content: flex-start;">
                <span>
                    <span class="badge rounded-pill bg-danger text-white">
                        No. @Model.AgentID
                    </span>
                </span>
                <h3 style="margin-left: 10px;">
                    <!-- Add margin-left for spacing if needed -->
                    @Model.Name
                </h3>
            </div>

            <h5>Role</h5>
            <div class="card-text p-1">@Model.Role</div>

            <h5>Biography</h5>
            <div class="card-text p-1">@Model.Biography</div>

            <p></p>

            <h5>Special Abilities</h5>
            <div class="card-text p-1">Q - @Model.Q_Ability, E - @Model.E_Ability, C - @Model.C_Ability, X - @Model.X_Ability</div>
        </div>

        <div class="col-2">
            <!-- space between text and image -->
        </div>

        <div class="col-4" style="float:right">
            <img src="~/Images/AgentIcons/@Model.AgentImage" style="width: 197px; height: 300px; float:right" />
        </div>

    </div>
</div>

ValorantSln/Views/Shared/WeaponSummary.cshtml
@model Weapon

<div class="card card-outline-primary m-1 p-1">
    <div class="row">

        <div class="col-6">
            <div class="bg-faded p-1" style="display: flex; justify-content: flex-start;">
                <span>
                    <span class="badge rounded-pill bg-danger text-white">
                        No. @Model.WeaponID
                    </span>
                </span>
                <h3 style="margin-left: 10px;">
                    <!-- Add margin-left for spacing if needed -->
                    @Model.WeaponName
                </h3>
            </div>

            <h5>Role</h5>
            <div class="card-text p-1">@Weapon.Role</div>

            <h5>Biography</h5>
            <div class="card-text p-1">@Weapon.Biography</div>

            <p></p>

            <h5>Special Abilities</h5>
            <div class="card-text p-1">Q - @Model.Q_Ability, E - @Model.E_Ability, C - @Model.C_Ability, X - @Model.X_Ability</div>
        </div>

        <div class="col-2">
            <!-- space between text and image -->
        </div>

        <div class="col-4" style="float:right">
            <img src="~/Images/AgentIcons/@Model.AgentImage" style="width: 197px; height: 300px; float:right" />
        </div>

    </div>
</div>

ValorantSln/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>
        Valorant Website
    </title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">
            <a asp-action="Index" asp-controller="Home">
                <img src="Images/valorant_logo.jpg" alt="" class="no-decoration" width="50" height="50" />
            </a>
        </span>
        <span style="margin-left:3rem"><a class="btn btn-primary" asp-action="AgentList" asp-controller="Agent">Agents</a></span>
        <span style="margin-left:3rem"><a class="btn btn-primary" asp-action="Weapon" asp-controller="Weapon">Weapon</a></span>
    </div>
    <div class="row m-1 p-1">
        <div id="roles" class="col-3">
            <!--<vc:agent-navigation />--->
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>